title = "Pansmith's Cookbook"

[params.author]
name = "Pansmith's Cookbook"
image = "img/pansmith.png"
headline = "A place for the everything else."
bio = "You likely know me better from elsewhere."
links = [
  { github = "https://github.com/thepansmith" }
]
